---
# inventory
- name: Inventory.yml - Create inventory object
  ansible.controller.inventory:
    name: "{{ inventory }}"
    description: "{{ description }}"
    organization: "{{ organization }}"
    state: present

# when you have your inventory file stored in a git repository
- name: Inventory.yml - Add an inventory source
  ansible.controller.inventory_source:
    name: "{{ inventory_source }}"
    description: "{{ description }}"
    inventory: "{{ inventory }}"
    credential: "{{ credential  }}"
    overwrite: true
    update_on_launch: true
    organization: "{{ organization }}"
    source: scm
    source_path: "{{ source_path }}"
    source_project: "{{ project }}"
    state: present
    # scm_branch: "{{ project_git_branch }}"
    overwrite_vars: true # Override vars in child groups and hosts with those from external source.
    overwrite: true    # Delete child groups and hosts not found in source.

# Incase you need to hard-code inventory on AAP

# # CISCO
# - name: Inventory.yml - Create cisco host object
#   ansible.controller.host:
#     name: "{{ item }}"
#     description: "{{ common_description }}"
#     inventory: "{{ redhat_test_inventory_name }}"
#     state: present
#     enabled: true
#   loop: "{{ test_cisco_grp_hosts }}"

# - name: Inventory.yml - Create cisco host group object
#   ansible.controller.group:
#     name: "{{ test_cisco_grp }}"
#     description: "{{ common_description }}"
#     inventory: "{{ redhat_test_inventory_name  }}"
#     hosts: "{{ item }}"
#     preserve_existing_hosts: True
#     preserve_existing_children: True
#   loop: "{{ test_cisco_grp_hosts }}"




